### PR TITLE
add dualboot support for xiaomi devices

### PR DESCRIPTION
**Pull request by M1cha**

### CODE REVIEW

**Comment by kennethso168** [comment]
Thank you very much. It's great as it can extend compatibility to xiaomi devices.
But before merging the request I'd like to confirm two things:
1. Have you test it on a xiaomi device? Does everything (including the reboot, screenshot, etc. options) works?
2. I hope that for non-xiaomi devices, the extra dualboot options will not show up as it's useless. Is that the case?
Once again, thank you very much.

**Comment by M1cha** [comment]
1. yes I own a xiaomi device(aries/mi2(s)) and everything works just fine
2. Since I've added the check "supportsDualboot" but I just saw, that the settings for this entry is always visible. is it possible to hide settings in a preferenceactivity?

**Comment by kennethso168** [comment]
I think you can do something like this in the onCreate(Bundle savedInstanceState) method:

``` java
...
boolean supportDualBoot; //initialized before
if(supportDualBoot){
    getPreferenceScreen().findPreference("pref_rebootsub_system12").setEnabled(true);
}else{
    getPreferenceScreen().findPreference("pref_rebootsub_system12").setEnabled(false);
}
...
```

**Comment by M1cha** [comment]
I've found a way to hide them so users don't get confused by a disabled option.
the commit has been added to this pull request

**Comment by kennethso168** [comment]
OK I merged the commit. But I'll redirect all user support questions regarding xiaomi devices to you as I know nothing about xiaomi devices. In what way would you like to answer them? (e.g. email?) Thank you.

**Comment by kennethso168** [comment]
Hi
The "system1" option appeared in the reboot method menu for my Xperia Z. I'll make some minor changes, the most important one being:

``` java
if(System1Enabled&&DualBoot.supportsDualboot()){
    mRebootItemList.add(new BasicIconListItem(mRebootSystem1Str, null, mRebootIcon, null));
    rebootSubMenu[cnt] = SEQ_REBOOT_SYSTEM1;
    cnt++;
}
```

I've added &&DualBoot.supportsDualboot() after System1Enabled

See if that breaks the functionality on xiaomi devices in return after I commit and push the relevant files. Thanks

**Comment by M1cha** [comment]
you should add this flag to if(prefSystem12Enabled) some lines above this code.

and replace this:
pref.getBoolean("pref_rebootsub_system12", true);
with this:
pref.getBoolean("pref_rebootsub_system12", false);

**Comment by kennethso168** [comment]
I've also made that change as well. But this doesn't fix the problem

**Comment by M1cha** [comment]
if(prefSystem12Enabled && DualBoot.supportsDualboot())
doesn't fix the problem? sounds impossible to me because everything is false then.

**Comment by kennethso168** [comment]
Oh I've already done that before in the latest commit and it does fix the
problem. Please see the latest commit on GitHub and see if it still works
on xiaomi

**Comment by kennethso168** [comment]
Dear M1cha,
Thank you very much for your work for Advanced Reboot Menu(APM).
I'm writing to inform you that I'm planning to make a new package of APM (tentatively something called APM2). The APM2 will feature a lot of new functions and a redesigned UI. The new package will not be open source. And I'm thinking of implementing in-app donations and purchases for extra functions. (The package will still be provided free of charge on xposed repository as well as Play store)
Therefore, I'm asking if you agree I integrate your work into APM2. You can be assured that no part of your work will be charged, and can be freely used by all users concerned. I'll also make relevant attributions.
I sincerely hope for your consent so that my app can be made a lot better. I look forward to your favorable reply.

Regards,
Kenneth

**Comment by M1cha** [comment]
Sounds like a bad decision in my opinion since I love opensource but I won't deny using my code :)

**Comment by kennethso168** [comment]
Thank you very much!

**Pull request merged**
